title: Билкова аптека
email: bilkova.apteka@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Това е блог за лични впечатления и преживявания. 
  Приятелите ще видят тук себе си, любопитния читател ще види интересни, важни и общочовешки теми. 
  Семейството ми ще ме види по начин чрез който надявам се да ме разбере. 
  Най-сетне, пиша този блог за да разбера и себе си по-добре.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bilkova.eu" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5

timezone: Europe/Sofia

# Build settings
theme: minima
plugins:
  - jekyll-feed 
  - jekyll-paginate
  - jekyll-date-localization
  
tag_page_layout: tag
tag_page_dir: tag


date_locale: bg
locales_path: _locales
