title: Билкова аптека
author: Деян Стоянов
email: bilkova.apteka@proton.me
description: >-
  Това е блог за лични впечатления и преживявания. 
  Приятелите ще видят тук себе си, любопитния читател ще види интересни, важни и общочовешки теми. 
  Семейството ми ще ме види по начин чрез който надявам се да ме разбере. 
  Най-сетне, пиша този блог за да разбера и себе си по-добре.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bilkova.eu" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5

timezone: Europe/Sofia

# Build settings
theme: minima
  
feed:
  posts_limit: 20000
  
tag_page_layout: tag
tag_page_dir: tag


date_locale: bg
locales_path: _locales

google_analytics: G-SVXL226WEF

exclude: [to_do.txt, README.md, LICENSE, delete_meta_files.sh, backup.sh, CNAME]