name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Scripts to run'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: move the current drafts to posts
      run: mv _drafts/$(date +'%Y-%m-%d')* _posts/
    - name: git add
      run: git add _posts/$(date +'%Y-%m-%d')*
    - name: git rm
      run: git rm _drafts/$(date +'%Y-%m-%d')*
    - name: git commit 
      run: git commit -m 'Deploy todays posts'
    - name: git push 
      run: git push origin main
