name: Cron workflow

on:
  schedule:
    - cron:  '0 8 * * *'
    - cron:  '15 13 * * *'

jobs:
  run_scripts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: move the current drafts to posts
      run: mv _drafts/$(date +'%Y-%m-%d')* _posts/ || echo "No drafts for posts today."
    - name: git
      run: |
          git config --local user.name deyanstoyanov850618
          git add _posts/$(date +'%Y-%m-%d')* || echo "No posts to add in git today."
          git rm _drafts/$(date +'%Y-%m-%d')* || echo "No drafts to delete in git today."
          if ! git diff-index --quiet HEAD; then
             git commit -m 'Deploy todays posts'
             git push origin main
          fi
