name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Scripts to run'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: move the current drafts to posts
      run: mv _drafts/$(date +"%Y-%m-%d")* _posts/
    - uses: EndBug/add-and-commit@v9
      with:
        message: Add todays posts - $(date+"%Y-%m-%d")
        add: _posts/$(date+"%Y-%m-%d")*
        remove: _drafts/$(date+"%Y-%m-%d")*
