name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Moves todays posts from _drafts to _posts'
jobs:
  run_scripts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: move the current drafts to posts
      run: mv _drafts/$(date +'%Y-%m-%d')* _posts/
    - name: git
      run: |
          git config --local user.name deyanstoyanov850618
          git add _posts/$(date +'%Y-%m-%d')*
          git rm _drafts/$(date +'%Y-%m-%d')*
          git commit -m 'Deploy todays posts'
          git push origin main
